# Generated by Django 3.1.2 on 2021-01-19 02:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, unique=True)),
                ('client_company_name', models.CharField(max_length=200)),
                ('client_company_address', models.TextField()),
                ('client_company_phone', models.CharField(max_length=200)),
                ('gc_name1', models.CharField(max_length=200)),
                ('gc_name2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RefInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RefStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('interfacelinks', models.TextField()),
                ('is_live', models.BooleanField(default=False)),
                ('eccompanyid', models.CharField(max_length=200)),
                ('customerid', models.CharField(max_length=200)),
                ('api_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.client')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_timestamp', models.DateTimeField(default=datetime.datetime(2021, 1, 19, 10, 2, 6, 110819))),
                ('current_status', models.CharField(max_length=500)),
                ('current_status_details', models.TextField()),
                ('api_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.client')),
            ],
        ),
        migrations.CreateModel(
            name='APIIntegrationSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_active_discussion_date', models.DateTimeField()),
                ('important_notes', models.TextField()),
                ('answers_to_probing_questions', models.TextField()),
                ('environment_credentials', models.TextField()),
                ('client_webhook_link', models.TextField()),
                ('client_webhook_sample', models.TextField()),
                ('remarks', models.TextField()),
                ('waybill_format_notes', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='tracker.client')),
                ('interface_shared', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.refinterface')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.refstage')),
            ],
        ),
    ]
