# Generated by Django 3.1.2 on 2021-01-22 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210119_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiintegrationsummary',
            name='last_active_discussion_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='currentstatus',
            name='entry_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 8, 9, 16, 647047)),
        ),
    ]
