# Generated by Django 3.1.2 on 2021-01-22 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20210122_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiintegrationsummary',
            name='last_active_discussion_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='currentstatus',
            name='entry_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 8, 11, 27, 728882)),
        ),
    ]
