# Generated by Django 3.1.2 on 2021-01-22 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20210122_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gc_name1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='gc_name2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='currentstatus',
            name='entry_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 12, 20, 35, 559697)),
        ),
    ]
