# Generated by Django 3.1.2 on 2021-01-22 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20210122_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiintegrationsummary',
            name='answers_to_probing_questions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='apiintegrationsummary',
            name='client_webhook_link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='apiintegrationsummary',
            name='client_webhook_sample',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='apiintegrationsummary',
            name='environment_credentials',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='apiintegrationsummary',
            name='important_notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='apiintegrationsummary',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='apiintegrationsummary',
            name='waybill_format_notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_company_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='currentstatus',
            name='current_status_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='currentstatus',
            name='entry_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 17, 14, 18, 355035)),
        ),
        migrations.AlterField(
            model_name='environmentcredential',
            name='interfacelinks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='refinterface',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='refstage',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
