# Generated by Django 3.1.2 on 2021-01-27 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20210122_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentstatus',
            old_name='api_integration',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='environmentcredential',
            old_name='api_integration',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='apiintegrationsummary',
            name='answers_to_probing_questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiintegrationsummary',
            name='client_webhook_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiintegrationsummary',
            name='client_webhook_sample',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiintegrationsummary',
            name='environment_credentials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiintegrationsummary',
            name='important_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiintegrationsummary',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiintegrationsummary',
            name='waybill_format_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentstatus',
            name='entry_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 15, 52, 42, 302361)),
        ),
    ]
